import { useState, useRef } from "react";
import { useSettings } from "../contexts/settings-context";
import { useExpenses } from "../contexts/expense-context";
import { Button } from "./ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { AlertCircle, RefreshCw, Wallet, Download, Upload } from "lucide-react";

const SUPPORTED_CURRENCIES = ["PHP", "USD", "EUR", "JPY", "GBP", "AUD", "CAD", "SGD"];

export function SettingsPage() {
  const { currency, lastUpdated, changeCurrency, refreshRates } = useSettings();
  const { convertAllFinancialData } = useExpenses();
  
  const [selectedCurrency, setSelectedCurrency] = useState(currency);
  const [isConverting, setIsConverting] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleCurrencyChange = async () => {
    if (selectedCurrency === currency) return;
    const confirm = window.confirm(`WARNING: This will permanently recalculate all past transactions, budgets, and bills from ${currency} to ${selectedCurrency}. Do you wish to proceed?`);
    if (!confirm) return;

    setIsConverting(true);
    const success = await changeCurrency(selectedCurrency, convertAllFinancialData);
    setIsConverting(false);

    if (!success) {
      alert("Failed to convert currency. Please ensure you have an active internet connection to download the latest exchange rates.");
      setSelectedCurrency(currency);
    }
  };

  const handleRefreshRates = async () => {
    setIsRefreshing(true);
    const success = await refreshRates();
    setIsRefreshing(false);
    if (success) alert("Exchange rates successfully updated!");
    else alert("Failed to reach exchange server. You may be offline.");
  };

// 👇 PHASE 3: EXPORT BACKUP (Updated for Android Support)
  const handleExportBackup = async () => {
    const backupData = {
      local_months: localStorage.getItem('local_months'),
      local_accounts: localStorage.getItem('local_accounts'),
      local_transactions: localStorage.getItem('local_transactions'),
      local_categories: localStorage.getItem('local_categories'),
      local_budgets: localStorage.getItem('local_budgets'),
      local_recurring: localStorage.getItem('local_recurring'),
      app_currency: localStorage.getItem('app_currency'),
    };
    
    const jsonString = JSON.stringify(backupData, null, 2);
    const filename = `finance_backup_${new Date().toISOString().split('T')[0]}.json`;

    try {
      // 1. Try the Native Android/iOS Share Sheet first
      const file = new File([jsonString], filename, { type: "application/json" });
      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({ 
          files: [file], 
          title: "Finance Backup Export",
          text: "Here is your local backup file for the Expense Tracker app."
        });
        return; // Stop here if native share succeeds
      }
    } catch (err) { 
      console.log("Share API failed or was cancelled by user", err); 
    }

    // 2. Fallback for Desktop Browsers (Windows/Mac)
    const blob = new Blob([jsonString], { type: "application/json;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // 👇 PHASE 3: IMPORT BACKUP
  const handleImportBackup = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const confirm = window.confirm("WARNING: Importing a backup will completely overwrite your current data. This cannot be undone. Proceed?");
    if (!confirm) {
      if (fileInputRef.current) fileInputRef.current.value = "";
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const data = JSON.parse(e.target?.result as string);
        if (data.local_months) localStorage.setItem('local_months', data.local_months);
        if (data.local_accounts) localStorage.setItem('local_accounts', data.local_accounts);
        if (data.local_transactions) localStorage.setItem('local_transactions', data.local_transactions);
        if (data.local_categories) localStorage.setItem('local_categories', data.local_categories);
        if (data.local_budgets) localStorage.setItem('local_budgets', data.local_budgets);
        if (data.local_recurring) localStorage.setItem('local_recurring', data.local_recurring);
        if (data.app_currency) localStorage.setItem('app_currency', data.app_currency);
        
        alert("Backup restored successfully! The application will now reload.");
        window.location.reload(); // Force full app reload to pull new local storage
      } catch (err) {
        alert("Invalid backup file. Please ensure it is a valid .json file generated by this application.");
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 sm:py-8 pb-24">
      <div className="mb-8">
        <p className="text-xs uppercase tracking-widest text-muted-foreground font-mono mb-1">Configuration</p>
        <h1 className="text-2xl font-semibold tracking-tight">App Settings</h1>
      </div>

      <section className="mb-10">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4">Global Currency Engine</h2>
        <div className="bg-card border border-border rounded-2xl p-5 shadow-sm space-y-5">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-primary/10 rounded-lg text-primary mt-1"><Wallet className="h-5 w-5" /></div>
            <div className="flex-1">
              <label className="text-sm font-medium block mb-1">Base Currency</label>
              <p className="text-xs text-muted-foreground mb-3 leading-relaxed">
                Changing your base currency will mathematically convert your entire historical database to match the new format based on today's live exchange rates.
              </p>
              <div className="flex gap-2">
                <Select value={selectedCurrency} onValueChange={setSelectedCurrency}>
                  <SelectTrigger className="w-[120px]"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {SUPPORTED_CURRENCIES.map(c => <SelectItem key={c} value={c}>{c}</SelectItem>)}
                  </SelectContent>
                </Select>
                <Button onClick={handleCurrencyChange} disabled={selectedCurrency === currency || isConverting}>
                  {isConverting ? "Converting..." : "Apply Conversion"}
                </Button>
              </div>
            </div>
          </div>
          <div className="border-t border-border pt-4 flex items-center justify-between text-xs text-muted-foreground">
            <div className="flex items-center gap-1.5">
              <AlertCircle className="h-4 w-4" />
              <span>Rates last synced: <span className="font-mono">{lastUpdated || "Never"}</span></span>
            </div>
            <Button variant="ghost" size="sm" onClick={handleRefreshRates} disabled={isRefreshing} className="h-7 px-2">
              <RefreshCw className={`h-3.5 w-3.5 mr-1 ${isRefreshing ? "animate-spin" : ""}`} /> Sync Rates
            </Button>
          </div>
        </div>
      </section>

      {/* PHASE 3: DATA SAFETY LOGIC */}
      <section>
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4">Data Management</h2>
        <div className="bg-card border border-border rounded-2xl p-5 shadow-sm divide-y divide-border">
          <div className="flex items-center justify-between pb-4">
            <div>
              <p className="text-sm font-medium">Export Local Backup</p>
              <p className="text-xs text-muted-foreground mt-0.5">Download your ledger as a .json file.</p>
            </div>
            <Button onClick={handleExportBackup} variant="outline" size="sm" className="gap-2"><Download className="h-4 w-4"/> Export</Button>
          </div>
          <div className="flex items-center justify-between pt-4">
            <div>
              <p className="text-sm font-medium">Import Backup</p>
              <p className="text-xs text-muted-foreground mt-0.5 text-destructive">Warning: Overwrites current data.</p>
            </div>
            {/* Hidden file input triggered by the button */}
            <input type="file" accept=".json" ref={fileInputRef} onChange={handleImportBackup} className="hidden" />
            <Button onClick={() => fileInputRef.current?.click()} variant="outline" size="sm" className="gap-2"><Upload className="h-4 w-4"/> Import</Button>
          </div>
        </div>
      </section>
    </div>
  );
}